# Generated by Django 5.0.4 on 2024-09-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('volume', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'Напиток',
                'verbose_name_plural': 'Напитки',
                'db_table': 'Drinks',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extra_price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'verbose_name': 'Инградиент',
                'verbose_name_plural': 'Инградиенты',
                'db_table': 'Ingradient',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Burger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.ManyToManyField(blank=True, to='menu.ingredient')),
            ],
            options={
                'verbose_name': 'Бургер',
                'verbose_name_plural': 'Бургеры',
                'db_table': 'Burgers',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('size', models.CharField(choices=[('small', 'Small (25cm)'), ('medium', 'Medium (30cm)'), ('large', 'Large (40cm)')], max_length=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ingredients', models.ManyToManyField(blank=True, to='menu.ingredient')),
            ],
            options={
                'verbose_name': 'Пица',
                'verbose_name_plural': 'Пицы',
                'db_table': 'Pizza',
                'ordering': ['price'],
            },
        ),
    ]
