# Generated by Django 5.0.4 on 2024-09-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_categories_burger_slug_drink_slug_pizza_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='burger',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='burgers/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='drink',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drinks/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pizzas/', verbose_name='Изображение'),
        ),
    ]
