# Generated by Django 5.0.4 on 2024-09-23 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_burger_image_drink_image_pizza_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
