# Generated by Django 5.0.4 on 2024-11-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_delete_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='volume',
            new_name='size',
        ),
    ]
